In [1]:
import numpy as np
import pandas as pd

1. Reading the Rounds2 files.

In [34]:
df=pd.read_csv('rounds2 (1).csv',encoding='ANSI')
df.head()

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0

1. Reading the companies.txt files.

In [20]:
df1=pd.read_table('companies (1).txt')
df1

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/Organization/-Qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/Organization/-The-One-Of-Them-Inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/Organization/004-Technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
...,...,...,...,...,...,...,...,...,...,...
66363,/Organization/Zznode-Science-And-Technology-Co...,ZZNode Science and Technology,http://www.zznode.com,Enterprise Software,operating,CHN,22,Beijing,Beijing,NaN
66364,/Organization/Zzzzapp-Com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
66365,/Organization/ÃEron,ÃERON,http://www.aeron.hu/,NaN,operating,NaN,NaN,NaN,NaN,01-01-2011
66366,/Organization/Ã”Asys-2,Ã”asys,http://www.oasys.io/,Consumer Electronics|Internet of Things|Teleco...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2014
66367,/Organization/Ä°Novatiff-Reklam-Ve-Tanä±Tä±M-H...,Ä°novatiff Reklam ve TanÄ±tÄ±m Hizmetleri Tic,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,operating,NaN,NaN,NaN,NaN,NaN

2. How many unique companies are present in rounds2?

In [23]:
df['company_permalink'].nunique()

90247

3. How many unique companies are present in the companies file?

In [24]:
df1['permalink'].nunique()

66368

4.Write the code to convert companies[‘permalink’] and Round2[‘company_permalink’] columns
to uppercase.

In [40]:
df.company_permalink = df.company_permalink.str.upper()
df.head()

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/ORGANIZATION/-FAME,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/ORGANIZATION/-QOUNTER,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/ORGANIZATION/0-6-COM,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0

In [39]:
df1.permalink = df1.permalink.str.upper()
df1.head()

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/ORGANIZATION/-FAME,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/ORGANIZATION/-QOUNTER,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/ORGANIZATION/0-6-COM,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/ORGANIZATION/004-TECHNOLOGIES,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010

5. Are there any companies in the rounds2 file which are not present in companies.txt ?

In [42]:
dfn = df[~ df["company_permalink"].isin(df1["permalink"])]
dfn

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
729,/ORGANIZATION/51WOFANG-Æ— Å¿§Æˆ‘Æˆ¿,/funding-round/346b9180d276a74e0fbb2825e66c6f5b,venture,A,06-07-2015,5000000.0
45176,/ORGANIZATION/HUIZUCHE-COM-ÆƑ Ç§ŸÈ½¦,/funding-round/8f8a32dbeeb0f831a78702f83af78a36,seed,NaN,18-09-2014,NaN
54751,/ORGANIZATION/LAWPÃ DÃ­,/funding-round/56a8ba75784c0028e2eacd0c0e205119,grant,NaN,23-03-2015,5000.0

In [44]:
dfn1 = df1[~ df1["permalink"].isin(df["company_permalink"])]
dfn1

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
426,/ORGANIZATION/51WOFANG-Æ— Å¿§Æˆ‘Æˆ¿,51wofang æ— å¿§æˆ‘æˆ¿,http://www.51wofang.com,NaN,closed,NaN,NaN,NaN,NaN,01-01-2014
26139,/ORGANIZATION/HUIZUCHE-COM-ÆƑ Ç§ŸÈ½¦,Huizuche.com æƒ ç§Ÿè½¦,http://huizuche.com,NaN,closed,NaN,NaN,NaN,NaN,24-04-2014
31693,/ORGANIZATION/LAWPÃ DÃ­,LawPadi,http://lawpadi.com/,Advice|Internet|Legal,closed,NGA,5,Lagos,Lagos,01-07-2015

6. Merge the two data frames so that all variables (columns) in the company's frame are added
to the rounds2 data frame. Name the merged frame master_dataframe. How many observations
are present in master_frame ?

In [118]:
master_dataframe=df.merge(df1,left_on='company_permalink', right_on='permalink')

7. Write the code to drop the redundant column ‘'company_permalink' from the
master_dataframe.

In [119]:
no_rows = len(master_dataframe)
print("Number of rows in master_dataframe:", len(master_dataframe))

Number of rows in master_dataframe: 114946

In [120]:
master_dataframe.drop("company_permalink", axis='columns', inplace=True)

8. Write the code to find the percentage missing value (column-wise) in master_dataframe. Drop
unnecessary columns.

In [121]:
for col in master_dataframe:
    total_nan_in_col = master_dataframe[col].isnull().sum()
    percent_nan_in_col = total_nan_in_col/no_rows * 100
    print(col, percent_nan_in_col, "%")

funding_round_permalink 0.0 %
funding_round_type 0.0 %
funding_round_code 72.90988812137873 %
funded_at 0.0 %
raised_amount_usd 17.38990482487429 %
permalink 0.0 %
name 0.000869973726793451 %
homepage_url 5.336418840151028 %
category_list 2.9648704609120804 %
status 0.0 %
country_code 7.54789205365998 %
state_code 9.520992466027527 %
region 8.843282932855427 %
city 8.840673011675047 %
founded_at 17.852730847528406 %

Removing column `funding_round_code`

In [122]:
master_dataframe.drop("funding_round_code", axis='columns', inplace=True)

9. Create a pivot table to compare the mean and median values for ‘raised_amount_usd’ and
‘funding_round_type’ across different funding round categories..

In [123]:
master_dataframe.pivot_table(index='funding_round_type',values='raised_amount_usd',aggfunc=['mean','median'])

                                   mean            median
                      raised_amount_usd raised_amount_usd
funding_round_type
angel                      9.586945e+05          400000.0
convertible_note           1.453439e+06          272000.0
debt_financing             1.704353e+07         1100000.0
equity_crowdfunding        5.383682e+05          100000.0
grant                      4.302600e+06          202658.0
non_equity_assistance      4.112031e+05           60000.0
post_ipo_debt              1.687046e+08        19950000.0
post_ipo_equity            8.218249e+07        12262852.5
private_equity             7.330859e+07        20000000.0
product_crowdfunding       1.363131e+06          183915.0
secondary_market           7.964963e+07        32600000.0
seed                       7.198180e+05          275000.0
undisclosed                1.924237e+07         1018680.0
venture                    1.174908e+07         5000000.0

10. Filter the master_dataframe on ‘raised_amount_usd’ such as ‘raised_amount_usd’ lie
between 4 Millions to 15 Millions.

In [139]:
def isBetweenRange(x):
    return x > 4000000 and x < 15000000
master_dataframe[master_dataframe['raised_amount_usd'].apply(lambda x: isBetweenRange(x))]

,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,10000000.0,/ORGANIZATION/-FAME,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
12,/funding-round/e1cfcbe1bdf4c70277c5f29a3482f24e,venture,19-07-2014,8900000.0,/ORGANIZATION/0XDATA,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
21,/funding-round/11c228f58831bc7ed337ef69ecc560c2,private_equity,01-02-2015,6000000.0,/ORGANIZATION/1-800-PUBLICRELATIONS-INC-,"1-800-PublicRelations, Inc.",http://www.1800publicrelations.com,Internet Marketing|Media|Public Relations,operating,USA,NY,New York City,New York,24-10-2013
22,/funding-round/b952cbaf401f310927430c97b68162ea,venture,17-03-2015,5000000.0,/ORGANIZATION/1-MAINSTREAM,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,acquired,USA,CA,SF Bay Area,Cupertino,01-03-2012
46,/funding-round/645b4cd895450b8e0268027cd7813047,venture,04-11-2015,6602694.0,/ORGANIZATION/1001-MENUS,ZenChef,http://zenchef.com/en/,Local Businesses|Restaurants,operating,FRA,A8,Paris,Paris,20-11-2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114918,/funding-round/85443f5438bfd50104b9591eabc95c94,grant,26-03-2014,7500000.0,/ORGANIZATION/ZYOMYX-INC,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114919,/funding-round/b4fce7f8a13267353d57db09099800e8,venture,11-07-2013,14219999.0,/ORGANIZATION/ZYOMYX-INC,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114927,/funding-round/c05aab2155e390066d51c6852ff61464,grant,11-09-2009,5400000.0,/ORGANIZATION/ZYRAZ-TECHNOLOGY,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114928,/funding-round/e949f077c943db197f20e43c2eb8d0e6,venture,09-10-2009,7991547.0,/ORGANIZATION/ZYRAZ-TECHNOLOGY,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114933,/funding-round/7ea37c0ff4132b084832039a9380d34e,venture,16-12-2004,8500000.0,/ORGANIZATION/ZYSTOR,Zystor,http://www.zystor.com,Biotechnology,acquired,USA,WI,Milwaukee,Milwaukee,NaN

11.Identify the top 9 countries in terms of highest investment in ‘venture’ fund type.

In [125]:
master_dataframe[master_dataframe['funding_round_type'] == "venture"].sort_values(by='raised_amount_usd', ascending=False).head(9)

,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
37568,/funding-round/a1495c088d886c8a4f4ce74403b77385,venture,21-10-2006,1.760000e+10,/ORGANIZATION/FREESCALE,Freescale Semiconductor,http://www.freescale.com,Semiconductors,ipo,USA,TX,Austin,Austin,01-01-1953
60204,/funding-round/07e345b61646adffc65946de6a1c88d9,venture,30-06-2003,4.700000e+09,/ORGANIZATION/MEDIAVAST,MediaVast,NaN,Advertising|Broadcasting|Content,acquired,USA,NY,New York City,New York,01-01-1999
104170,/funding-round/7a617d3521e9a71816c8d5cbcd4c49b0,venture,06-06-2014,1.200000e+09,/ORGANIZATION/UBER,Uber,http://www.uber.com,Automotive|Design|Limousines|Public Transporta...,operating,USA,CA,SF Bay Area,San Francisco,01-03-2009
104163,/funding-round/1fa1e079dd45f9d615ce1469ed9090fb,venture,04-12-2014,1.200000e+09,/ORGANIZATION/UBER,Uber,http://www.uber.com,Automotive|Design|Limousines|Public Transporta...,operating,USA,CA,SF Bay Area,San Francisco,01-03-2009
112170,/funding-round/0022fc712b8a48fc6b7341c6aa3b42a5,venture,22-12-2014,1.100000e+09,/ORGANIZATION/XIAOMI,Xiaomi,http://www.mi.com,Consumer Electronics|Mobile,operating,CHN,22,Beijing,Beijing,04-04-2010
93040,/funding-round/3cbfa3a38fe9a74b04f6eaae8b5bc478,venture,20-01-2015,1.000000e+09,/ORGANIZATION/SPACE-EXPLORATION-TECHNOLOGIES,Space Exploration Technologies,http://www.spacex.com,Aerospace|Space Travel,operating,USA,CA,Los Angeles,Hawthorne,01-01-2002
91672,/funding-round/1609f1ba4de61c4760c91dc69f4ae980,venture,30-09-2015,1.000000e+09,/ORGANIZATION/SOCIAL-FINANCE,SoFi,http://www.sofi.com,Education|Finance|Financial Services|Peer-to-Peer,operating,USA,CA,SF Bay Area,San Francisco,01-04-2011
104173,/funding-round/c738765257ab10e721f1a02d5af54681,venture,31-07-2015,1.000000e+09,/ORGANIZATION/UBER,Uber,http://www.uber.com,Automotive|Design|Limousines|Public Transporta...,operating,USA,CA,SF Bay Area,San Francisco,01-03-2009
36400,/funding-round/af6ac1c9d2f3050fd5e1530be3b9565f,venture,29-07-2014,1.000000e+09,/ORGANIZATION/FLIPKART,Flipkart,http://www.flipkart.com,E-Commerce|Online Shopping,operating,IND,19,Bangalore,Bangalore,01-09-2007

12. Create the ‘main_category’ column by extracting the main sector using the column
‘category_list’.

In [146]:
master_dataframe['category_list'] = master_dataframe['category_list'].astype('string')
def getMainCategory(x):
    if isinstance(x, str):
        return x.split("|")[0]
    else: return 'nan'

main_category = []
for x in master_dataframe['category_list']:
    main_category.append(getMainCategory(x))
master_dataframe['main_category'] = main_category

In [147]:
master_dataframe

,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at,main_category
0,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,TypeC,/ORGANIZATION/-FAME,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN,Media
1,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,14-10-2014,TypeC,/ORGANIZATION/-QOUNTER,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014,Application Platforms
2,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,01-03-2014,TypeA,/ORGANIZATION/-QOUNTER,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014,Application Platforms
3,/funding-round/650b8f704416801069bb178a1418776b,venture,30-01-2014,TypeA,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN,Apps
4,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,19-03-2008,TypeA,/ORGANIZATION/0-6-COM,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007,Curated Web
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114941,/funding-round/8f6d25b8ee4199e586484d817bceda05,convertible_note,01-03-2014,TypeA,/ORGANIZATION/ZZZZAPP-COM,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012,Advertising
114942,/funding-round/ff1aa06ed5da186c84f101549035d4ae,seed,01-05-2013,TypeA,/ORGANIZATION/ZZZZAPP-COM,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012,Advertising
114943,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,01-08-2014,TypeC,/ORGANIZATION/ÃERON,ÃERON,http://www.aeron.hu/,<NA>,operating,NaN,NaN,NaN,NaN,01-01-2011,nan
114944,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,01-01-2015,TypeA,/ORGANIZATION/Ã”ASYS-2,Ã”asys,http://www.oasys.io/,Consumer Electronics|Internet of Things|Teleco...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2014,Consumer Electronics
114945,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,01-10-2013,TypeA,/ORGANIZATION/Ä°NOVATIFF-REKLAM-VE-TANÄ±TÄ±M-H...,Ä°novatiff Reklam ve TanÄ±tÄ±m Hizmetleri Tic,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,operating,NaN,NaN,NaN,NaN,NaN,Consumer Goods

13. Using the user defined function convert the ‘rasied_amount_used’ column into a categorical
column as followa)
If the amount is less than 5 Millions then recode as TypeA.
b) If the amount is greater than 5 Millions and less than 7 Millions then recode as TypeB.
c) If the amount is greater than 7 Millions then recode as TypeC.

In [141]:
def getCategory(x):
    if x < 5000000:
        return "TypeA"
    elif x >= 5000000 and x < 7000000:
        return "TypeB"
    else: return "TypeC"
#     match x:
#         case x < 5000000:
#             return "TypeA"
#         case x >= 5000000 and x < 7000000:
#             return "TypeB"
#         case x >= 7000000:
#             return "TypeC"
master_dataframe['raised_amount_usd'] = master_dataframe['raised_amount_usd'].apply(lambda x: getCategory(x))

In [142]:
master_dataframe

,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,TypeC,/ORGANIZATION/-FAME,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,14-10-2014,TypeC,/ORGANIZATION/-QOUNTER,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,01-03-2014,TypeA,/ORGANIZATION/-QOUNTER,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
3,/funding-round/650b8f704416801069bb178a1418776b,venture,30-01-2014,TypeA,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
4,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,19-03-2008,TypeA,/ORGANIZATION/0-6-COM,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114941,/funding-round/8f6d25b8ee4199e586484d817bceda05,convertible_note,01-03-2014,TypeA,/ORGANIZATION/ZZZZAPP-COM,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
114942,/funding-round/ff1aa06ed5da186c84f101549035d4ae,seed,01-05-2013,TypeA,/ORGANIZATION/ZZZZAPP-COM,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
114943,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,01-08-2014,TypeC,/ORGANIZATION/ÃERON,ÃERON,http://www.aeron.hu/,<NA>,operating,NaN,NaN,NaN,NaN,01-01-2011
114944,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,01-01-2015,TypeA,/ORGANIZATION/Ã”ASYS-2,Ã”asys,http://www.oasys.io/,Consumer Electronics|Internet of Things|Teleco...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2014
114945,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,01-10-2013,TypeA,/ORGANIZATION/Ä°NOVATIFF-REKLAM-VE-TANÄ±TÄ±M-H...,Ä°novatiff Reklam ve TanÄ±tÄ±m Hizmetleri Tic,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,operating,NaN,NaN,NaN,NaN,NaN